apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: api-port
      protocol: TCP
      port: 3040
      targetPort: 3040
    - name: get-port
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: server-port
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: serverdos-port
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: socket-port
      protocol: TCP
      port: 3050
      targetPort: 3050
      name: authentication-port
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
